### ISSUE TITLE
Please unblock AstoriaUWP if you can...

### ISSUE THREAD

**Issue by mediaexplorer74** [Ticomware/Warthog-Run#1]
Hi, Carl.... from Ticomware.....  How are You?
Are You the developer of AstoriaUWP? ... I forked this project (solution) ... Sometimes I try to RnD it...
Please unblock (erase status "Archived") AstoriaUWP if you can... because AstoriaUWP project's Issues not available.
Best wishes,
 Andrey aka MediaExplorer

**Comment by cbialorucki** [comment]
Got it; I'll unarchive it.

**Comment by cbialorucki** [comment]
Done.
